### ISSUE TITLE
DynVolc.xml  AND WP11-DDSS-036_GAZVOLC.xml issues

### ISSUE THREAD

**Issue by epos-eu** [epos-eu/EPOS-DCAT-AP#112]
@FlahertyMcCoillean  
we refer to the files
https://github.com/epos-eu/EPOS-DCAT-AP/blob/master/examples/WP11/DynVolc.xml

https://github.com/epos-eu/EPOS-DCAT-AP/blob/master/examples/WP11/WP11-DDSS-036_GAZVOLC.xml

We Found the following issues:

1. The following link 
http://opgc.fr/vobs/rest2/req.php/dynvolc/epos-dcat-ap/41 defined in the webservice description
allows you to download the epos-dcat file.
We would need the endpoint of a webservice where we can have access to data in a parametrised way. Where is it reported?

2. The following link 
http://opgc.fr/vobs/rest2/req.php/gazvolc/epos-dcat-ap/41 defined in the webservice description
allows you to download the epos-dcat file.
We would need the endpoint of a webservice where we can have access to data in a parametrised way. Where is it reported?

**Comment by emmdelage** [comment]
Dear Flaherty,
1) http://opgc.fr/vobs/rest2/req.php/dynvolc
can have access to data (metadata refering to data) in a parametrised way
only with timestart and timeend for the moment
http://opgc.fr/vobs/rest2/req.php/dynvolc?timestart=2013-07-01T00:00:00Z&timeend=2015-07-31T00:00:00Z
2) WP11-DDSS-036_GAZVOLC.xml is in stand by due to manager relocation

**Comment by manuelasbarra** [comment]
WP11-DDSS-036-DynVolc.xml has been integrated
WP11-DDSS-036_GAZVOLC.xml can't be integrated
