### ISSUE TITLE
Metadata editor popup is off screen and not moveable

### ISSUE THREAD

**Issue by nmtoken** [epos-eu/EPOS-DCAT-AP#227]
![metadataeditor](https://user-images.githubusercontent.com/1692891/39583193-74c1a3c4-4ee7-11e8-8f6f-ccf1bb2b8292.png)

When trying to use the metadata editor to add an operation, the popup appears at the bottom of the screen and is not moveable, making it impossible to add details required.

**Comment by rrabissoni** [comment]
Hi James, 
I didn't get if you are trying to put that url directly into the tool: if yes, this won't work since it is not an EPOS-DCAT-AP XML.
On the other hand, recreating webservices and operations manually with the tool is the right way, but probably you are experiencing browser incompatiblity. Which one are you using? and which operating system? Actually I have to tell you that I developed the tool testing it only on Chrome for Mac, so I don't know how it behaves on different browsers.
Let me know!
R

**Comment by danielebailo** [comment]
Sorry Guys, this repository is for EPOS-DCAT-AP metadata representation issues only.
I've to close this one. 

As written in the document, issues are now handled by writing to riccardo.rabissoni@ingv.it

However in the next metadata call we will discuss about potential sharing of MDT editor on github.

**Comment by nmtoken** [comment]
Where should I file a bug report, as we were asked to report issues in the email
