### ISSUE TITLE
contactPoint for a webservice

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#27]
Literals like `mailto:support@institution` will be supported as IDs when a Person is expected. Mainly because on some cases there will be real persons, but in some others a support team (not an Organisation) will be responsible for the contact. For those cases, the `mailto`will be considered a schema similar to `orcid` and the mail will be the ID.
This will apply also fort others entities.

**Comment by rpaciello** [comment]
done.

**Comment by nmtoken** [comment]
Be aware that for INSPIRE metadata (version 2.0.1),  the minimum requirement for a contact about a web service is Organization name and contact email.  **TG Requirement C.6**.

The email address needs to be a functioning email address of the responsible party. 

The _recommendation_ (**C.2)** for Organization name, is that it should be given in full, without abbreviations.  It is also recommended that to use an email address of the organization, instead of a personal email address.

**Comment by danielebailo** [comment]
In the current EPOS-DCAT-AP with RDF/turtle serialisation contact points are represented by a "ContactPoint" class which can be both a Person or an Organisation or non physical entity (like support team).
See UML diagram here https://github.com/epos-eu/EPOS-DCAT-AP/blob/EPOS-DCAT-AP-shapes/EPOS_DCAT-AP_0.10.png

See also this example https://github.com/epos-eu/EPOS-DCAT-AP/blob/e30a43c994f2df69a728e13cb7c3ac1052815f80/examples/example_WP15.ttl#L18
