### ISSUE TITLE
Changes in Keywords (web service)

### ISSUE THREAD

**Issue by javiquinte** [epos-eu/EPOS-DCAT-AP#38]
The Keywords attribute will be a Literal list of comma-separated values. Change cardinality to 1..1 in the xsd and in the documentation/specification. TCSs should provide a controlled vocabulary list and there will be no limit on the amount of keywords.

**Comment by rpaciello** [comment]
done

**Comment by sgrellet** [comment]
We should use URIs for keywords. This is way more usable by the API/GUI
But this doesn't work well in one keyword element being a list of terms.

Can we rollback on this and with Keyword being (1.*) so that we can have 
- the URI to the vocab in an attribute
- the human readable name as the content ?

Example 
<dcat:keyword xlink:href="http://www.eionet.europa.eu/gemet/en/concept/3650">Geology</dcat:keyword>
<dcat:keyword xlink:href="http://sweet.jpl.nasa.gov/2.3/matrEquipment.owl#Borehole">Borehole</dcat:keyword>

**Comment by danielebailo** [comment]
This is fixed revised EPOS-DCAT-AP with  RDF/turtle serialisation and within the several call/meetings we had.
