### ISSUE TITLE
PIC 

### ISSUE THREAD

**Issue by jan-michalek** [epos-eu/EPOS-DCAT-AP#80]
Link where to find the PIC - ID of organisation from the European Commission:
https://ec.europa.eu/research/participants/portal/desktop/en/organisations/register_sec.html

**Comment by nmtoken** [comment]
"British Geological Survey" doesn't return any results :(

**Comment by sgrellet** [comment]
do you know of a website under ec.europa.eu where we can point to an organisation using its PIC ?
something like 'ec.europa.eu/PIC/999993662' that, if it existed, will point on some page dedicated to BRGM ?
otherwise we have others like 'http://viaf.org/viaf/150807757/rdf.xml' (thanks Damian) that is initially for library. The RDF view is interesting as it provides several sameAs to other identification schemes and also makes use of schema.org

@nmtoken : NERC does work :)

**Comment by danielebailo** [comment]
Identifier of organisations are managed by the Granularity Database.
I can therefore close this old issue.
