### ISSUE TITLE
Multiple oraganizations with the same PIC

### ISSUE THREAD

**Issue by spinto** [epos-eu/EPOS-DCAT-AP#99]
Hello. If I use the PIC as identifier for the organization, how can I handle multiple organizations sharing the same PIC (e.g. different institutes of CNR and CNR itself)? I think the organization identifier shall be unique, otherwise there will be errors.

**Comment by nmtoken** [comment]
Same applies to BGS.  BGS the organizational entity doesn't have a PIC, instead we come under NERC (currently).  NERC has several individual/independent organizations/research centres such as BGS, CEH, BAS, and NOC.

**Comment by ulbricht** [comment]
At the moment there is no global identifier system that works for everybody. Does VIAF or INSI work for CNR sub-institutions? BGS has records: https://viaf.org/viaf/136554353 , http://isni.org/isni/0000000119565915

**Comment by spinto** [comment]
INSI seems to work for CNR and its institutes

**Comment by sgrellet** [comment]
ISNI works for BRGM as well (http://www.isni.org/isni/0000000121846484)
I prefer this to the 'PIC:xxxx' pattern because it resolves to a persistant URI (see http://www.isni.org/how-isni-works#HowItWorks_LinkedData) and is linked to ISO activities
We can force an 'ISNI flavoured' XML return (http://www.isni.org/isni/0000000121846484.xml)

But I doesn't seem we can have content negociation asking for rdf, turle on it.
Ex : curl -v -L -H "Accept: application/rdf+xml" "http://www.isni.org/isni/0000000121846484" doesn't work

**Comment by danielebailo** [comment]
Identifiers of institutions will be managed by Granularity database (@wxlfrank maintains this).

I can therefore close this issue.
